#+TITLE: 2015 Troop 675 Robotics Merit Badge Class Competition:  Robotic Plutonium Carry
#+AUTHOR: Maurice Ling
#+DATE: 2015-08-23
* Competition Date, Location, and Schedule
  - Date:  Monday, August 31, 2015
  - Time:  6:00-8:30pm
  - Location:  Light of Christ Church Fellowship Hall
  - Schedule:
    - 6:00 pm Setup
    - 6:30 pm Design Review with Judges
    - 7:00 pm Competition Start
    - 8:00 pm Competition results and discussion
* Summary
  1. Transport radioactive plutonium payload from one reactor to another.
  2. Plutonium payload will take the form of a ping pong ball.
  3. Begin and end with a human-controlled segment to load and unload
     the payload.
  4. Autonomously navigate a transport course between the load and unloading areas.
* Terminology
  1. We refer to the humans participating in the competition as the /participant(s)/
     and the device as the /robot/.
  2. The /payload/ refers to the ping pong ball in the competition.
  3. The /competition/ refers to each participator's performance in the 
     competition course.
  4. The /over-all competition/ refers to the entire competition with all participants.
  5. The participant's /entry/ into the competition includes the hardware, software (program), 
     and documentation (Engineering Notebook)

* Competition Specifications
** Hardware
   1. The robot shall be programmed by the participants.
   2. The robot shall use one or more processors/boards
   3. Robot shall fit in the plastic box distributed at the first class.
      (8.25"x6.0"x6.5")
** Programming
   1. The robot shall not be re-programmed while the robot is in the competition course.
   2. There will be a 1 minute period prior to starting where the robot may be 
      calibrated or adjusted.
   3. The source code and/or logic flow, and design for the robots shall be available for judges to review.
   4. The participant may utilize libraries in the program.
   5. If code is copy and pasted from third party sources, the reference must be
      attributed in the code comments.
   6. The core code and logic shall be written by the participant.
** Time for Completion
   1. The robot shall complete the course in maximum of 5 minutes.
   2. Bonus points will be awarded for time achieved under 3 minutes 
      (see the Scoring section).
** Payload
   1. The payload shall be a regulation (non-radioactive) ping pong ball with a diameter
      of 40mm.
   2. The payload shall not be directly touched by the participant.
** Loading/Unloading
   1. The robot shall load payload from an 3-inch high elevated platform.
   2. The robot shall unload the payload onto a 3-inch high elevated platform.
   3. Loading and unloading may be done using manual (human-directed or controlled
      mechanisms).
   4. Loading/unloading mechanism must be part of the robot.  No mechanisms apart
      the robot shall be used.
** Transport Course
   1. The transport course shall be navigated autonomously by the robot.
   2. The payload shall remain with the robot during transport.
   3. The participant shall not manually intervene while the robot is within
      the transport course.
   4. The robot shall not make contact with walls or objects within the 
      transport course (see Point Penalties section).
   5. Obstacles and boundaries of the course will range in height from
      7/8 to 3.5 inches.
** Design Review
   - Designs shall be documented in your Engineering Notebook and include:
     1. Programming logic
     2. Mechanical/Physical design diagrams/sketches
     3. Circuit diagram
     4. Testing results
   - Designs shall be available for the Judges to review during the Design
     Review prior to start of the competition.
** Quarantine
   1. The Robot Display Table shall function as the quarantine area during the competition.
   2. The participant shall design a sign identifying his name and his robot's name
      for the Robot Display Table.
   3. All robots and IR controllers shall be quarantined 5 minutes prior to the 
      over-all competition start.
   4. No programming or robot modifications shall be made while quarantined.
   5. Once a participant has completed his competition, the next participant
      may retrieve his robot from quarantine and start preparing for his competition.
      This may include:
      - Calibration to the course.
      - Programming adjustments
      - Physical adjustments
   6. The participant shall receive a one minute warning to the start of
      his competition.  After the one minute expires, no changes may be 
      made to the robot.
   7. After each competition, the participant's robot and IR  controller must be returned to
      the quarantine table.
   
* Teamwork (optional)
  1. A scout may team up with one other scout. 
  2. Team must be decided by the end of the 2nd class.
  3. Each member of the team must understand how the entire robot operates.

* Scoring
  1. Completion of each segment (Load, transport, Unload) shall be +20 points.
  2. Complete design documentation in Engineering Notebook up to +30 points
     awarded as follows:
     1) Programming logic (+5)
     2) Physical design (+5)
     3) Circuit/Electrical design (+5)
     4) Testing Results (+5)
     5) Neatness/organization (+5)
     6) Elegant and innovative design (+5)
  3. Bonus Points
     1) Time Bonus
        - +10 for under 3 minutes
        - +20 for under 2 minutes
        - +30 for under 1 minute
  4. Point Penalties
     1) Each manual intervention by the participant during transport (-5)
     2) Each payload touch by the participant (-5)
     3) Each contact with obstacles or boundaries in the transport course (-1)
* Judge Panel
  1. Scoring will be done by an impartial judge panel.
  2. During the Design Review phase, the judges will individually
     review each the participant's entries ask the participants questions.
     Time spent with each participant is approximately 3 minutes.
  3. Each judge shall score the competitions individually, marking the score
     for each participant on a score sheet.
  4. At the completion of each competition, the judges will spend up to 2 minutes to 
     agree on the final score for the participant.
  5. Judges will be selected by the Merit Badge Counselor.
